import RPi.GPIO as GPIO

GPIO_PIN_1WIRE = 4
GPIO_PIN_DHT11 = 17
GPIO_PIN_LED_FEEDING = 27
GPIO_PIN_BUTTON_FEEDING = 22
GPIO_PIN_SERVO_FEEDING = 18
GPIO_PIN_LCD_SDA = 2
GPIO_PIN_LCD_SDC = 3
GPIO_PIN_LED_WATERING = 0
GPIO_PIN_BUTTON_WATERING = 5
GPIO_PIN_RELAY1_WATERING = 6
GPIO_PIN_RELAY2_WATERING = 13
GPIO_PIN_RELAY3_WATERING = 19
GPIO_PIN_RELAY4_WATERING = 26

# Sets INPUT/OUTPUT modes

GPIO.setmode(GPIO.BCM)
#GPIO.setup(GPIO_PIN_1WIRE, GPIO.IN) # nothing to do, handled by kernel
GPIO.setup(GPIO_PIN_DHT11, GPIO.IN)
GPIO.setup(GPIO_PIN_LED_FEEDING, GPIO.OUT)
GPIO.setup(GPIO_PIN_BUTTON_FEEDING, GPIO.IN)
GPIO.setup(GPIO_PIN_SERVO_FEEDING, GPIO.OUT)
#GPIO.setup(GPIO_PIN_LCD_SDA, GPIO.OUT) # must be in ALT0 mode, just don't touch it
#GPIO.setup(GPIO_PIN_LCD_SDC, GPIO.OUT) # must be in ALT0 mode
GPIO.setup(GPIO_PIN_LED_WATERING, GPIO.OUT)
GPIO.setup(GPIO_PIN_BUTTON_WATERING, GPIO.IN)
GPIO.setup(GPIO_PIN_RELAY1_WATERING, GPIO.OUT)
GPIO.setup(GPIO_PIN_RELAY2_WATERING, GPIO.OUT)
GPIO.setup(GPIO_PIN_RELAY3_WATERING, GPIO.OUT)
GPIO.setup(GPIO_PIN_RELAY4_WATERING, GPIO.OUT)

# Defines whether outputs are LOW or HIGH

GPIO.output(GPIO_PIN_LED_FEEDING, GPIO.LOW)
GPIO.output(GPIO_PIN_LED_WATERING, GPIO.LOW)
GPIO.output(GPIO_PIN_RELAY1_WATERING, GPIO.HIGH) # Surprisingly, HIGH=Relay "off"
GPIO.output(GPIO_PIN_RELAY2_WATERING, GPIO.HIGH)
GPIO.output(GPIO_PIN_RELAY3_WATERING, GPIO.HIGH)
GPIO.output(GPIO_PIN_RELAY4_WATERING, GPIO.HIGH)