language: python3

key:

before_script:

script:
  - pip install --user --upgrade pip virtualenv python-coveralls
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - make -C server test
  - coverage run --source=server -a server/database_test.py
  - coverage run --source=server -a server/server_grpc_test.py
  - coverage run --source=server -a server/server_web_test.py
  - deactivate

after_success:
  - coveralls