language: python3

key: server/requirements.txt

before_script: make install-server

script:
  pip install --user --upgrade pip virtualenv
  virtualenv -p python3 .venv
  source .venv/bin/activate
  $(MAKE) -C server install
  $(MAKE) -C server test
  deactivate