language: python3
python:
  - "3.7"

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - make -C server test
  - make -C server coverage
  - rm -f .coverage
  - cat server/.coverage > .coverage.server
  - make -C client/python test
  - make -C client/python coverage
  - cat client/python/.coverage > .coverage.client
  - cat .coverage_client
  - cat .coverage_server
  - coverage combine
  - cat .coverage
  - coveralls
  - deactivate