language: python3

key:

before_script:

script:
  - pip install --user --upgrade pip virtualenv python-coveralls
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - make -C server test
  - make -C server coverage
  - deactivate

after_success:
  - coveralls