language: python3

key:

before_script:

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - pytest
  - rm -f .coverage
  - coverage run -m py.test
  - coveralls
  - deactivate