language: python3

key:

before_script:

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - $(MAKE) -C server install
  - $(MAKE) -C server test
  - deactivate