language: python3
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - make -C server test
  - make -C server coverage
  - rm -f .coverage
  - cat server/.coverage
  - cat server/.coverage > .coverage
  - make -C client/python test
  - make -C client/python coverage
  - cat client/python/.coverage
  - cat client/python/.coverage >> .coverage
  - coveralls
  - deactivate