language: python3
python:
  - "3.7"

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C client/python install
  - make -C client/python test
  - deactivate