language: python3

key:

before_script:

script:
  - pip install --user --upgrade pip virtualenv
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - make -C server install
  - make -C server test
  - make coverage
  - rm -f .coverage
  - cat server/.coverage > .coverage
  - coveralls
  - deactivate