// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufs.proto

package gaia

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	FeedingModuleActivated   bool     `protobuf:"varint,1,opt,name=feeding_module_activated,json=feedingModuleActivated,proto3" json:"feeding_module_activated,omitempty"`
	WateringModuleActivated  bool     `protobuf:"varint,2,opt,name=watering_module_activated,json=wateringModuleActivated,proto3" json:"watering_module_activated,omitempty"`
	FeedingModuleCronstring  string   `protobuf:"bytes,3,opt,name=feeding_module_cronstring,json=feedingModuleCronstring,proto3" json:"feeding_module_cronstring,omitempty"`
	WateringModuleCronstring string   `protobuf:"bytes,4,opt,name=watering_module_cronstring,json=wateringModuleCronstring,proto3" json:"watering_module_cronstring,omitempty"`
	WateringPump_1Duration   int32    `protobuf:"varint,5,opt,name=watering_pump_1_duration,json=wateringPump1Duration,proto3" json:"watering_pump_1_duration,omitempty"`
	WateringPump_2Duration   int32    `protobuf:"varint,6,opt,name=watering_pump_2_duration,json=wateringPump2Duration,proto3" json:"watering_pump_2_duration,omitempty"`
	WateringPump_3Duration   int32    `protobuf:"varint,7,opt,name=watering_pump_3_duration,json=wateringPump3Duration,proto3" json:"watering_pump_3_duration,omitempty"`
	WateringPump_4Duration   int32    `protobuf:"varint,8,opt,name=watering_pump_4_duration,json=wateringPump4Duration,proto3" json:"watering_pump_4_duration,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_8710ad5a1726d424, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetFeedingModuleActivated() bool {
	if m != nil {
		return m.FeedingModuleActivated
	}
	return false
}

func (m *Config) GetWateringModuleActivated() bool {
	if m != nil {
		return m.WateringModuleActivated
	}
	return false
}

func (m *Config) GetFeedingModuleCronstring() string {
	if m != nil {
		return m.FeedingModuleCronstring
	}
	return ""
}

func (m *Config) GetWateringModuleCronstring() string {
	if m != nil {
		return m.WateringModuleCronstring
	}
	return ""
}

func (m *Config) GetWateringPump_1Duration() int32 {
	if m != nil {
		return m.WateringPump_1Duration
	}
	return 0
}

func (m *Config) GetWateringPump_2Duration() int32 {
	if m != nil {
		return m.WateringPump_2Duration
	}
	return 0
}

func (m *Config) GetWateringPump_3Duration() int32 {
	if m != nil {
		return m.WateringPump_3Duration
	}
	return 0
}

func (m *Config) GetWateringPump_4Duration() int32 {
	if m != nil {
		return m.WateringPump_4Duration
	}
	return 0
}

type SystemStatus struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Memory               string   `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	DiskUsage            string   `protobuf:"bytes,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	Processes            string   `protobuf:"bytes,4,opt,name=processes,proto3" json:"processes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemStatus) Reset()         { *m = SystemStatus{} }
func (m *SystemStatus) String() string { return proto.CompactTextString(m) }
func (*SystemStatus) ProtoMessage()    {}
func (*SystemStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8710ad5a1726d424, []int{1}
}

func (m *SystemStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatus.Unmarshal(m, b)
}
func (m *SystemStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatus.Marshal(b, m, deterministic)
}
func (m *SystemStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatus.Merge(m, src)
}
func (m *SystemStatus) XXX_Size() int {
	return xxx_messageInfo_SystemStatus.Size(m)
}
func (m *SystemStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatus proto.InternalMessageInfo

func (m *SystemStatus) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *SystemStatus) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *SystemStatus) GetDiskUsage() string {
	if m != nil {
		return m.DiskUsage
	}
	return ""
}

func (m *SystemStatus) GetProcesses() string {
	if m != nil {
		return m.Processes
	}
	return ""
}

type Status struct {
	AuthenticationToken  string        `protobuf:"bytes,1,opt,name=authentication_token,json=authenticationToken,proto3" json:"authentication_token,omitempty"`
	LocalTimestamp       string        `protobuf:"bytes,2,opt,name=local_timestamp,json=localTimestamp,proto3" json:"local_timestamp,omitempty"`
	CurrentConfig        *Config       `protobuf:"bytes,3,opt,name=current_config,json=currentConfig,proto3" json:"current_config,omitempty"`
	SystemStatus         *SystemStatus `protobuf:"bytes,4,opt,name=system_status,json=systemStatus,proto3" json:"system_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8710ad5a1726d424, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetAuthenticationToken() string {
	if m != nil {
		return m.AuthenticationToken
	}
	return ""
}

func (m *Status) GetLocalTimestamp() string {
	if m != nil {
		return m.LocalTimestamp
	}
	return ""
}

func (m *Status) GetCurrentConfig() *Config {
	if m != nil {
		return m.CurrentConfig
	}
	return nil
}

func (m *Status) GetSystemStatus() *SystemStatus {
	if m != nil {
		return m.SystemStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "gaia.Config")
	proto.RegisterType((*SystemStatus)(nil), "gaia.SystemStatus")
	proto.RegisterType((*Status)(nil), "gaia.Status")
}

func init() { proto.RegisterFile("protobufs.proto", fileDescriptor_8710ad5a1726d424) }

var fileDescriptor_8710ad5a1726d424 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x5f, 0x8b, 0xd3, 0x40,
	0x14, 0xc5, 0x89, 0xbb, 0x1b, 0x37, 0x77, 0xbb, 0xbb, 0x30, 0xea, 0x36, 0x8a, 0x42, 0xe9, 0x8b,
	0x7d, 0x2a, 0x34, 0x29, 0x54, 0xc4, 0x17, 0xa9, 0xaf, 0x82, 0xa4, 0xf5, 0x79, 0x98, 0x26, 0xd3,
	0x38, 0xb4, 0x93, 0x09, 0xf3, 0x47, 0x29, 0x7e, 0x4b, 0x9f, 0xfd, 0x30, 0x4b, 0xa6, 0x93, 0x26,
	0x6d, 0xda, 0xb7, 0xcc, 0x39, 0xf7, 0xc7, 0x3d, 0xdc, 0x7b, 0x03, 0x8f, 0xa5, 0x14, 0x5a, 0xac,
	0xcc, 0x5a, 0x8d, 0xed, 0x17, 0xba, 0xce, 0x09, 0x23, 0xc3, 0xff, 0x57, 0xe0, 0xcf, 0x45, 0xb1,
	0x66, 0x39, 0xfa, 0x04, 0xe1, 0x9a, 0xd2, 0x8c, 0x15, 0x39, 0xe6, 0x22, 0x33, 0x5b, 0x8a, 0x49,
	0xaa, 0xd9, 0x6f, 0xa2, 0x69, 0x16, 0x7a, 0x03, 0x6f, 0x74, 0x9b, 0x3c, 0x39, 0xff, 0xbb, 0xb5,
	0xbf, 0xd6, 0x2e, 0xfa, 0x0c, 0x6f, 0xff, 0x10, 0x4d, 0xe5, 0x59, 0xf4, 0x85, 0x45, 0xfb, 0x75,
	0xc1, 0x19, 0xf6, 0xa4, 0x6b, 0x2a, 0x45, 0xa1, 0x74, 0x55, 0x1b, 0x5e, 0x0d, 0xbc, 0x51, 0x90,
	0xf4, 0x8f, 0xda, 0xce, 0x0f, 0x36, 0xfa, 0x02, 0xef, 0x4e, 0xfb, 0xb6, 0xe0, 0x6b, 0x0b, 0x87,
	0xc7, 0x8d, 0x5b, 0xf4, 0x0c, 0x0e, 0x1e, 0x2e, 0x0d, 0x2f, 0xf1, 0x04, 0x67, 0x46, 0x12, 0xcd,
	0x44, 0x11, 0xde, 0x0c, 0xbc, 0xd1, 0x4d, 0xf2, 0xa6, 0xf6, 0x7f, 0x18, 0x5e, 0x4e, 0xbe, 0x39,
	0xb3, 0x0b, 0x46, 0x0d, 0xe8, 0x77, 0xc1, 0xe8, 0x32, 0x18, 0x37, 0xe0, 0xcb, 0x2e, 0x18, 0x5f,
	0x06, 0xa7, 0x0d, 0x78, 0xdb, 0x05, 0xa7, 0x35, 0x38, 0xfc, 0x0b, 0xbd, 0xc5, 0x4e, 0x69, 0xca,
	0x17, 0x9a, 0x68, 0xa3, 0xd0, 0x13, 0xf8, 0xa6, 0xd4, 0x8c, 0x53, 0xbb, 0xd1, 0x20, 0x71, 0xaf,
	0x4a, 0xe7, 0x94, 0x0b, 0xb9, 0xb3, 0xeb, 0x0a, 0x12, 0xf7, 0x42, 0x1f, 0x00, 0x32, 0xa6, 0x36,
	0xd8, 0x28, 0x92, 0x53, 0xb7, 0x8e, 0xa0, 0x52, 0x7e, 0x56, 0x02, 0x7a, 0x0f, 0x41, 0x29, 0x45,
	0x4a, 0x95, 0xa2, 0xca, 0xcd, 0xbb, 0x11, 0x86, 0xff, 0x3c, 0xf0, 0x5d, 0xdf, 0x09, 0xbc, 0x26,
	0x46, 0xff, 0xa2, 0x85, 0x66, 0xa9, 0x4d, 0x86, 0xb5, 0xd8, 0xd0, 0xc2, 0xa5, 0x78, 0x75, 0xec,
	0x2d, 0x2b, 0x0b, 0x7d, 0x84, 0xc7, 0xad, 0x48, 0xc9, 0x16, 0x57, 0x01, 0x95, 0x26, 0xbc, 0x74,
	0xd9, 0x1e, 0xac, 0xbc, 0xac, 0x55, 0x14, 0xc3, 0x43, 0x6a, 0xa4, 0xa4, 0x85, 0xc6, 0xa9, 0xbd,
	0x64, 0x9b, 0xf3, 0x2e, 0xea, 0x8d, 0xab, 0x0b, 0x1f, 0xef, 0xaf, 0x3b, 0xb9, 0x77, 0x35, 0xee,
	0xd8, 0x67, 0x70, 0xaf, 0xec, 0x60, 0xb0, 0xb2, 0x09, 0x6d, 0xfa, 0xbb, 0x08, 0xed, 0x99, 0xf6,
	0xcc, 0x92, 0x9e, 0x6a, 0xbd, 0x56, 0xbe, 0xfd, 0x7b, 0xe2, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x0e, 0xdc, 0xff, 0x50, 0x03, 0x00, 0x00,
}
