# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gaia_client.protobufs_pb2 as protobufs__pb2


class GaiaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/gaia.GaiaService/Ping',
        request_serializer=protobufs__pb2.Status.SerializeToString,
        response_deserializer=protobufs__pb2.Response.FromString,
        )
    self.ActionDone = channel.unary_unary(
        '/gaia.GaiaService/ActionDone',
        request_serializer=protobufs__pb2.ActionReport.SerializeToString,
        response_deserializer=protobufs__pb2.Response.FromString,
        )


class GaiaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ActionDone(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GaiaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=protobufs__pb2.Status.FromString,
          response_serializer=protobufs__pb2.Response.SerializeToString,
      ),
      'ActionDone': grpc.unary_unary_rpc_method_handler(
          servicer.ActionDone,
          request_deserializer=protobufs__pb2.ActionReport.FromString,
          response_serializer=protobufs__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gaia.GaiaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
