
/* tslint:disable */
// This file was generated from a topside template.
// Do not edit this file, edit the original template instead.

import * as __escape from 'escape-html';
__escape;

import __parent, { __Params as __ParentParams } from './layout.top'
export interface __Section {
    (parent: () => string): () => string;
}
export type __Params = {

} & __ParentParams

function __identity<T>(t: T): T {
    return t;
}
__identity;

function __safeSection(section?: __Section): __Section {
        return section ? section : __identity;
}
__safeSection;

export default function(__params?: __Params, __childSections?: {
            'content'?: __Section;
        }): string {


    let __safeChildSections: {
            'content'?: __Section;
        } = __childSections || {};
    __safeChildSections;
    const __sections: {
            'content': __Section;
        } = {
        "content": __safeSection(__safeChildSections["content"])
    };
    __sections;
    const __text = "\n" + (() => {
            const __sectionName = "content";
            __sections[__sectionName] = ((__parent: () => string) => __safeSection(__safeChildSections[__sectionName])(() => "\n\n<h2>Blockchain</h2>\n\n<div id=\"blockchain\">\n    <div class=\"block\">\n        <div class=\"id\">1</div>\n        <div class=\"value1\">10.4</div>\n        <div class=\"value2\">12.4</div>\n        <div class=\"hash\">9f86d08</div>\n        <svg class=\"icon icon-checkmark-outline\"><use xlink:href=\"#icon-checkmark-outline\"></use></svg>\n    </div>\n    <div class=\"block\">\n        <div class=\"id\">2</div>\n        <div class=\"value1\">12.4</div>\n        <div class=\"value2\">16.4</div>\n        <div class=\"hash\">659a2fe</div>\n        <svg class=\"icon icon-checkmark-outline\"><use xlink:href=\"#icon-checkmark-outline\"></use></svg>\n    </div>\n    <div class=\"block\">\n        <div class=\"id\">3</div>\n        <div class=\"value1\">13.4</div>\n        <div class=\"value2\">14.4</div>\n        <div class=\"hash\">f4f1b2b</div>\n        <svg class=\"icon icon-checkmark-outline\"><use xlink:href=\"#icon-checkmark-outline\"></use></svg>\n    </div>\n</div>\n\n\n"));
            return "";
        })() + "";
    __text;
    return __parent(__params, __sections);
};
//# sourceMappingURL=index.top.ts.map